# Generated by Django 4.0.3 on 2023-03-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_alter_automobilevo_model_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
